### PR TITLE
Add metrics tab to admin portal

### PR DESCRIPTION
**Pull request by JakeThurman**
**To test:**
1. `cd` to `web-dev` directory
2. `npm install && npm start`
3. Navigate to [http://localhost:8080/](http://localhost:8080/)
4. Observe the metrics WOW

These are just some simple metrics. But I was curious about something and got carried away :)

screen shot 2019-02-23 at 4 24 28 pm

### CODE REVIEW

**Comment by noahtallen** [comment]
😂

**Comment by noahtallen** [comment]
screen shot 2019-02-23 at 5 26 15 pm
screen shot 2019-02-23 at 5 26 23 pm

**Comment by noahtallen** [comment]
Can't get it to run locally because of a compiler error. Maybe it's because it can't find my firebase init file?

**Comment by JakeThurman** [comment]
@noahtallen Possibly, but I fixed the `AuthHandler.tsx` issue. Duh. I saw that earlier but it dissapeared. Good catch!

**Comment by noahtallen** [comment]
I'm now getting this error:
screen shot 2019-02-25 at 12 08 13 am

**Pull request merged**
